mindmap
  root((Expression))  
    TableExpressionBase
        FromSqlExpression
            Long history
            ::icon(fa fa-book)
            Popularisation
                British popular psychology author Tony Buzan
        JoinExpressionBase
            CrossApplyExpression
            CrossJoinExpression
            OuterApplyExpression
        PredicateJoinExpressionBase
            InnerJoinExpression
            LeftJoinExpression
            
        SelectExpression
      
        SetOperationBase
            UnionExpression
            ExceptExpression
            IntersectExpression
        TableExpression

        TableValuedFunctionExpression

        ValuesExpression
    SqlExpression
        AtTimeZoneExpression
        CaseExpression
        CollateExpression
        ColumnExpression
        DistinctExpression
        ExistsExpression
        InExpression
        LikeExpression
        RowNumberExpression
        RowValueExpression
        ScalarSubqueryExpression
        SqlBinaryExpression
        SqlConstantExpression
        SqlFragmentExpression
        SqlFunctionExpression
        SqlParameterExpression
        SqlUnaryExpression

    UpdateExpression
    DeleteExpression
    OrderingExpression
    ProjectionExpression

